### ISSUE TITLE
insert_row and insert_column have incorrect documentation

### ISSUE THREAD

**Issue by AntonBogun** [aardappel/treesheets#237]
In https://github.com/aardappel/treesheets/commit/dc8ac936aae6ca7a0939d4809f496953ee4e7e19 the ts_insert_rows and ts_insert_columns were changed to ts_insert_row and ts_insert_column, but the documentation was not changed accordingly.

**Comment by aardappel** [comment]
fixed in https://github.com/aardappel/treesheets/commit/8b7a15fa0420d470b65f56de81f5a0dd2396d64c

**Comment by AntonBogun** [comment]
Not quite fixed, the "insert n rows" is still there. Will make a pull request that will fix that along with adding more script functionality later.

**Comment by aardappel** [comment]
Look in the commit I linked.. the `s` was removed from the functions you mentioned.

**Comment by AntonBogun** [comment]
But not in the lobster_impl.cpp?
